api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/apiPlatform'
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: [ 'application/json','application/ld+json' ]
    formats:
        jsonld:
            mime_types: [ 'application/ld+json' ]
        json:
            mime_types: [ 'application/json','application/ld+json' ]
        html:
            mime_types: [ 'text/html' ]
        form:
            mime_types: [ 'multipart/form-data' ]
    swagger:
        versions: [3]
