doctrine:
    dbal:
        default_connection: postgres
        connections:
            postgres:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_pgsql'
                charset: utf8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: postgres
        entity_managers:
            postgres:
                connection: postgres
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App