#read
App\Entity\Group\Group:
    attributes:
        formats: [ 'json' ]
        output: App\DTO\Group\Output\GroupOutput
    properties:
        id:
            identifier: true
    collectionOperations:
        get:
            path: /group
            normalization_context:
                groups: [
                        'group:collection',
                        'user:base',
                        'groupMember:base',
                        'invitation:base'
                ]
            openapi_context:
                tags:
                    - Group
    itemOperations:
        get:
            path: /group/{id}
            normalization_context:
                groups: [
                        'group:item',
                        'user:base',
                        'post:collection',
                        'groupMember:base',
                        'invitation:base',
                        'event:collection'
                ]
            openapi_context:
                tags:
                    - Group
        delete:
            path: /group/{id}
            openapi_context:
                tags:
                    - Group
#write
App\DTO\Group\Input\GroupInput:
    attributes:
        formats: [ 'json' ]
        output: App\DTO\Group\Output\GroupOutput
    properties:
        id:
            identifier: true
    itemOperations:
        patch:
            path: /group/{id}
            denormalization_context:
                groups: [ 'group:patch' ]
            validation_groups: [ 'group:update' ]
            openapi_context:
                tags:
                    - Group
    collectionOperations:
        post:
            path: /group
            denormalization_context:
                groups: [ 'group:post' ]
            validation_groups: [ 'group:create' ]
            openapi_context:
                tags:
                    - Group